name    'lfisher47-grub'
version '0.0.1'
author  'Leah Fisher'
license 'Apache2'
project_page 'https://github.com/lfisher47/puppet-grub'
source  'git://github.com/lfisher47/puppet-grub'
summary 'grub STIG requirements'
description 'grub STIG requirements'
dependency 'domcleal/augeasproviders'
